const uuidv4 = require('uuid/v4');

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('regencies')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('regencies').insert([
        { id: '1101', province_id: '11', name: 'SIMEULUE' },
        { id: '1102', province_id: '11', name: 'ACEH SINGKIL' },
        { id: '1103', province_id: '11', name: 'ACEH SELATAN' },
        { id: '1104', province_id: '11', name: 'ACEH TENGGARA' },
        { id: '1105', province_id: '11', name: 'ACEH TIMUR' },
        { id: '1106', province_id: '11', name: 'ACEH TENGAH' },
        { id: '1107', province_id: '11', name: 'ACEH BARAT' },
        { id: '1108', province_id: '11', name: 'ACEH BESAR' },
        { id: '1109', province_id: '11', name: 'PIDIE' },
        { id: '1110', province_id: '11', name: 'BIREUEN' },
        { id: '1111', province_id: '11', name: 'ACEH UTARA' },
        { id: '1112', province_id: '11', name: 'ACEH BARAT DAYA' },
        { id: '1113', province_id: '11', name: 'GAYO LUES' },
        { id: '1114', province_id: '11', name: 'ACEH TAMIANG' },
        { id: '1115', province_id: '11', name: 'NAGAN RAYA' },
        { id: '1116', province_id: '11', name: 'ACEH JAYA' },
        { id: '1117', province_id: '11', name: 'BENER MERIAH' },
        { id: '1118', province_id: '11', name: 'PIDIE JAYA' },
        { id: '1171', province_id: '11', name: 'BANDA ACEH' },
        { id: '1172', province_id: '11', name: 'SABANG' },
        { id: '1173', province_id: '11', name: 'LANGSA' },
        { id: '1174', province_id: '11', name: 'LHOKSEUMAWE' },
        { id: '1175', province_id: '11', name: 'SUBULUSSALAM' },
        { id: '1201', province_id: '12', name: 'NIAS' },
        { id: '1202', province_id: '12', name: 'MANDAILING NATAL' },
        { id: '1203', province_id: '12', name: 'TAPANULI SELATAN' },
        { id: '1204', province_id: '12', name: 'TAPANULI TENGAH' },
        { id: '1205', province_id: '12', name: 'TAPANULI UTARA' },
        { id: '1206', province_id: '12', name: 'TOBA SAMOSIR' },
        { id: '1207', province_id: '12', name: 'LABUHAN BATU' },
        { id: '1208', province_id: '12', name: 'ASAHAN' },
        { id: '1209', province_id: '12', name: 'SIMALUNGUN' },
        { id: '1210', province_id: '12', name: 'DAIRI' },
        { id: '1211', province_id: '12', name: 'KARO' },
        { id: '1212', province_id: '12', name: 'DELI SERDANG' },
        { id: '1213', province_id: '12', name: 'LANGKAT' },
        { id: '1214', province_id: '12', name: 'NIAS SELATAN' },
        { id: '1215', province_id: '12', name: 'HUMBANG HASUNDUTAN' },
        { id: '1216', province_id: '12', name: 'PAKPAK BHARAT' },
        { id: '1217', province_id: '12', name: 'SAMOSIR' },
        { id: '1218', province_id: '12', name: 'SERDANG BEDAGAI' },
        { id: '1219', province_id: '12', name: 'BATU BARA' },
        { id: '1220', province_id: '12', name: 'PADANG LAWAS UTARA' },
        { id: '1221', province_id: '12', name: 'PADANG LAWAS' },
        { id: '1222', province_id: '12', name: 'LABUHAN BATU SELATAN' },
        { id: '1223', province_id: '12', name: 'LABUHAN BATU UTARA' },
        { id: '1224', province_id: '12', name: 'NIAS UTARA' },
        { id: '1225', province_id: '12', name: 'NIAS BARAT' },
        { id: '1271', province_id: '12', name: 'SIBOLGA' },
        { id: '1272', province_id: '12', name: 'TANJUNG BALAI' },
        { id: '1273', province_id: '12', name: 'PEMATANG SIANTAR' },
        { id: '1274', province_id: '12', name: 'TEBING TINGGI' },
        { id: '1275', province_id: '12', name: 'MEDAN' },
        { id: '1276', province_id: '12', name: 'BINJAI' },
        { id: '1277', province_id: '12', name: 'PADANGSIDIMPUAN' },
        { id: '1278', province_id: '12', name: 'GUNUNGSITOLI' },
        { id: '1301', province_id: '13', name: 'KEPULAUAN MENTAWAI' },
        { id: '1302', province_id: '13', name: 'PESISIR SELATAN' },
        { id: '1303', province_id: '13', name: 'SOLOK' },
        { id: '1304', province_id: '13', name: 'SIJUNJUNG' },
        { id: '1305', province_id: '13', name: 'TANAH DATAR' },
        { id: '1306', province_id: '13', name: 'PADANG PARIAMAN' },
        { id: '1307', province_id: '13', name: 'AGAM' },
        { id: '1308', province_id: '13', name: 'LIMA PULUH KOTA' },
        { id: '1309', province_id: '13', name: 'PASAMAN' },
        { id: '1310', province_id: '13', name: 'SOLOK SELATAN' },
        { id: '1311', province_id: '13', name: 'DHARMASRAYA' },
        { id: '1312', province_id: '13', name: 'PASAMAN BARAT' },
        { id: '1371', province_id: '13', name: 'PADANG' },
        { id: '1372', province_id: '13', name: 'SOLOK' },
        { id: '1373', province_id: '13', name: 'SAWAH LUNTO' },
        { id: '1374', province_id: '13', name: 'PADANG PANJANG' },
        { id: '1375', province_id: '13', name: 'BUKITTINGGI' },
        { id: '1376', province_id: '13', name: 'PAYAKUMBUH' },
        { id: '1377', province_id: '13', name: 'PARIAMAN' },
        { id: '1401', province_id: '14', name: 'KUANTAN SINGINGI' },
        { id: '1402', province_id: '14', name: 'INDRAGIRI HULU' },
        { id: '1403', province_id: '14', name: 'INDRAGIRI HILIR' },
        { id: '1404', province_id: '14', name: 'PELALAWAN' },
        { id: '1405', province_id: '14', name: 'S I A K' },
        { id: '1406', province_id: '14', name: 'KAMPAR' },
        { id: '1407', province_id: '14', name: 'ROKAN HULU' },
        { id: '1408', province_id: '14', name: 'BENGKALIS' },
        { id: '1409', province_id: '14', name: 'ROKAN HILIR' },
        { id: '1410', province_id: '14', name: 'KEPULAUAN MERANTI' },
        { id: '1471', province_id: '14', name: 'PEKANBARU' },
        { id: '1473', province_id: '14', name: 'D U M A I' },
        { id: '1501', province_id: '15', name: 'KERINCI' },
        { id: '1502', province_id: '15', name: 'MERANGIN' },
        { id: '1503', province_id: '15', name: 'SAROLANGUN' },
        { id: '1504', province_id: '15', name: 'BATANG HARI' },
        { id: '1505', province_id: '15', name: 'MUARO JAMBI' },
        { id: '1506', province_id: '15', name: 'TANJUNG JABUNG TIMUR' },
        { id: '1507', province_id: '15', name: 'TANJUNG JABUNG BARAT' },
        { id: '1508', province_id: '15', name: 'TEBO' },
        { id: '1509', province_id: '15', name: 'BUNGO' },
        { id: '1571', province_id: '15', name: 'JAMBI' },
        { id: '1572', province_id: '15', name: 'SUNGAI PENUH' },
        { id: '1601', province_id: '16', name: 'OGAN KOMERING ULU' },
        { id: '1602', province_id: '16', name: 'OGAN KOMERING ILIR' },
        { id: '1603', province_id: '16', name: 'MUARA ENIM' },
        { id: '1604', province_id: '16', name: 'LAHAT' },
        { id: '1605', province_id: '16', name: 'MUSI RAWAS' },
        { id: '1606', province_id: '16', name: 'MUSI BANYUASIN' },
        { id: '1607', province_id: '16', name: 'BANYU ASIN' },
        { id: '1608', province_id: '16', name: 'OGAN KOMERING ULU SELATAN' },
        { id: '1609', province_id: '16', name: 'OGAN KOMERING ULU TIMUR' },
        { id: '1610', province_id: '16', name: 'OGAN ILIR' },
        { id: '1611', province_id: '16', name: 'EMPAT LAWANG' },
        { id: '1612', province_id: '16', name: 'PENUKAL ABAB LEMATANG ILIR' },
        { id: '1613', province_id: '16', name: 'MUSI RAWAS UTARA' },
        { id: '1671', province_id: '16', name: 'PALEMBANG' },
        { id: '1672', province_id: '16', name: 'PRABUMULIH' },
        { id: '1673', province_id: '16', name: 'PAGAR ALAM' },
        { id: '1674', province_id: '16', name: 'LUBUKLINGGAU' },
        { id: '1701', province_id: '17', name: 'BENGKULU SELATAN' },
        { id: '1702', province_id: '17', name: 'REJANG LEBONG' },
        { id: '1703', province_id: '17', name: 'BENGKULU UTARA' },
        { id: '1704', province_id: '17', name: 'KAUR' },
        { id: '1705', province_id: '17', name: 'SELUMA' },
        { id: '1706', province_id: '17', name: 'MUKOMUKO' },
        { id: '1707', province_id: '17', name: 'LEBONG' },
        { id: '1708', province_id: '17', name: 'KEPAHIANG' },
        { id: '1709', province_id: '17', name: 'BENGKULU TENGAH' },
        { id: '1771', province_id: '17', name: 'BENGKULU' },
        { id: '1801', province_id: '18', name: 'LAMPUNG BARAT' },
        { id: '1802', province_id: '18', name: 'TANGGAMUS' },
        { id: '1803', province_id: '18', name: 'LAMPUNG SELATAN' },
        { id: '1804', province_id: '18', name: 'LAMPUNG TIMUR' },
        { id: '1805', province_id: '18', name: 'LAMPUNG TENGAH' },
        { id: '1806', province_id: '18', name: 'LAMPUNG UTARA' },
        { id: '1807', province_id: '18', name: 'WAY KANAN' },
        { id: '1808', province_id: '18', name: 'TULANGBAWANG' },
        { id: '1809', province_id: '18', name: 'PESAWARAN' },
        { id: '1810', province_id: '18', name: 'PRINGSEWU' },
        { id: '1811', province_id: '18', name: 'MESUJI' },
        { id: '1812', province_id: '18', name: 'TULANG BAWANG BARAT' },
        { id: '1813', province_id: '18', name: 'PESISIR BARAT' },
        { id: '1871', province_id: '18', name: 'BANDAR LAMPUNG' },
        { id: '1872', province_id: '18', name: 'METRO' },
        { id: '1901', province_id: '19', name: 'BANGKA' },
        { id: '1902', province_id: '19', name: 'BELITUNG' },
        { id: '1903', province_id: '19', name: 'BANGKA BARAT' },
        { id: '1904', province_id: '19', name: 'BANGKA TENGAH' },
        { id: '1905', province_id: '19', name: 'BANGKA SELATAN' },
        { id: '1906', province_id: '19', name: 'BELITUNG TIMUR' },
        { id: '1971', province_id: '19', name: 'PANGKAL PINANG' },
        { id: '2101', province_id: '21', name: 'KARIMUN' },
        { id: '2102', province_id: '21', name: 'BINTAN' },
        { id: '2103', province_id: '21', name: 'NATUNA' },
        { id: '2104', province_id: '21', name: 'LINGGA' },
        { id: '2105', province_id: '21', name: 'KEPULAUAN ANAMBAS' },
        { id: '2171', province_id: '21', name: 'B A T A M' },
        { id: '2172', province_id: '21', name: 'TANJUNG PINANG' },
        { id: '3101', province_id: '31', name: 'KEPULAUAN SERIBU' },
        { id: '3171', province_id: '31', name: 'JAKARTA SELATAN' },
        { id: '3172', province_id: '31', name: 'JAKARTA TIMUR' },
        { id: '3173', province_id: '31', name: 'JAKARTA PUSAT' },
        { id: '3174', province_id: '31', name: 'JAKARTA BARAT' },
        { id: '3175', province_id: '31', name: 'JAKARTA UTARA' },
        { id: '3201', province_id: '32', name: 'BOGOR' },
        { id: '3202', province_id: '32', name: 'SUKABUMI' },
        { id: '3203', province_id: '32', name: 'CIANJUR' },
        { id: '3204', province_id: '32', name: 'BANDUNG' },
        { id: '3205', province_id: '32', name: 'GARUT' },
        { id: '3206', province_id: '32', name: 'TASIKMALAYA' },
        { id: '3207', province_id: '32', name: 'CIAMIS' },
        { id: '3208', province_id: '32', name: 'KUNINGAN' },
        { id: '3209', province_id: '32', name: 'CIREBON' },
        { id: '3210', province_id: '32', name: 'MAJALENGKA' },
        { id: '3211', province_id: '32', name: 'SUMEDANG' },
        { id: '3212', province_id: '32', name: 'INDRAMAYU' },
        { id: '3213', province_id: '32', name: 'SUBANG' },
        { id: '3214', province_id: '32', name: 'PURWAKARTA' },
        { id: '3215', province_id: '32', name: 'KARAWANG' },
        { id: '3216', province_id: '32', name: 'BEKASI' },
        { id: '3217', province_id: '32', name: 'BANDUNG BARAT' },
        { id: '3218', province_id: '32', name: 'PANGANDARAN' },
        { id: '3271', province_id: '32', name: 'BOGOR' },
        { id: '3272', province_id: '32', name: 'SUKABUMI' },
        { id: '3273', province_id: '32', name: 'BANDUNG' },
        { id: '3274', province_id: '32', name: 'CIREBON' },
        { id: '3275', province_id: '32', name: 'BEKASI' },
        { id: '3276', province_id: '32', name: 'DEPOK' },
        { id: '3277', province_id: '32', name: 'CIMAHI' },
        { id: '3278', province_id: '32', name: 'TASIKMALAYA' },
        { id: '3279', province_id: '32', name: 'BANJAR' },
        { id: '3301', province_id: '33', name: 'CILACAP' },
        { id: '3302', province_id: '33', name: 'BANYUMAS' },
        { id: '3303', province_id: '33', name: 'PURBALINGGA' },
        { id: '3304', province_id: '33', name: 'BANJARNEGARA' },
        { id: '3305', province_id: '33', name: 'KEBUMEN' },
        { id: '3306', province_id: '33', name: 'PURWOREJO' },
        { id: '3307', province_id: '33', name: 'WONOSOBO' },
        { id: '3308', province_id: '33', name: 'MAGELANG' },
        { id: '3309', province_id: '33', name: 'BOYOLALI' },
        { id: '3310', province_id: '33', name: 'KLATEN' },
        { id: '3311', province_id: '33', name: 'SUKOHARJO' },
        { id: '3312', province_id: '33', name: 'WONOGIRI' },
        { id: '3313', province_id: '33', name: 'KARANGANYAR' },
        { id: '3314', province_id: '33', name: 'SRAGEN' },
        { id: '3315', province_id: '33', name: 'GROBOGAN' },
        { id: '3316', province_id: '33', name: 'BLORA' },
        { id: '3317', province_id: '33', name: 'REMBANG' },
        { id: '3318', province_id: '33', name: 'PATI' },
        { id: '3319', province_id: '33', name: 'KUDUS' },
        { id: '3320', province_id: '33', name: 'JEPARA' },
        { id: '3321', province_id: '33', name: 'DEMAK' },
        { id: '3322', province_id: '33', name: 'SEMARANG' },
        { id: '3323', province_id: '33', name: 'TEMANGGUNG' },
        { id: '3324', province_id: '33', name: 'KENDAL' },
        { id: '3325', province_id: '33', name: 'BATANG' },
        { id: '3326', province_id: '33', name: 'PEKALONGAN' },
        { id: '3327', province_id: '33', name: 'PEMALANG' },
        { id: '3328', province_id: '33', name: 'TEGAL' },
        { id: '3329', province_id: '33', name: 'BREBES' },
        { id: '3371', province_id: '33', name: 'MAGELANG' },
        { id: '3372', province_id: '33', name: 'SURAKARTA' },
        { id: '3373', province_id: '33', name: 'SALATIGA' },
        { id: '3374', province_id: '33', name: 'SEMARANG' },
        { id: '3375', province_id: '33', name: 'PEKALONGAN' },
        { id: '3376', province_id: '33', name: 'TEGAL' },
        { id: '3401', province_id: '34', name: 'KULON PROGO' },
        { id: '3402', province_id: '34', name: 'BANTUL' },
        { id: '3403', province_id: '34', name: 'GUNUNG KIDUL' },
        { id: '3404', province_id: '34', name: 'SLEMAN' },
        { id: '3471', province_id: '34', name: 'YOGYAKARTA' },
        { id: '3501', province_id: '35', name: 'PACITAN' },
        { id: '3502', province_id: '35', name: 'PONOROGO' },
        { id: '3503', province_id: '35', name: 'TRENGGALEK' },
        { id: '3504', province_id: '35', name: 'TULUNGAGUNG' },
        { id: '3505', province_id: '35', name: 'BLITAR' },
        { id: '3506', province_id: '35', name: 'KEDIRI' },
        { id: '3507', province_id: '35', name: 'MALANG' },
        { id: '3508', province_id: '35', name: 'LUMAJANG' },
        { id: '3509', province_id: '35', name: 'JEMBER' },
        { id: '3510', province_id: '35', name: 'BANYUWANGI' },
        { id: '3511', province_id: '35', name: 'BONDOWOSO' },
        { id: '3512', province_id: '35', name: 'SITUBONDO' },
        { id: '3513', province_id: '35', name: 'PROBOLINGGO' },
        { id: '3514', province_id: '35', name: 'PASURUAN' },
        { id: '3515', province_id: '35', name: 'SIDOARJO' },
        { id: '3516', province_id: '35', name: 'MOJOKERTO' },
        { id: '3517', province_id: '35', name: 'JOMBANG' },
        { id: '3518', province_id: '35', name: 'NGANJUK' },
        { id: '3519', province_id: '35', name: 'MADIUN' },
        { id: '3520', province_id: '35', name: 'MAGETAN' },
        { id: '3521', province_id: '35', name: 'NGAWI' },
        { id: '3522', province_id: '35', name: 'BOJONEGORO' },
        { id: '3523', province_id: '35', name: 'TUBAN' },
        { id: '3524', province_id: '35', name: 'LAMONGAN' },
        { id: '3525', province_id: '35', name: 'GRESIK' },
        { id: '3526', province_id: '35', name: 'BANGKALAN' },
        { id: '3527', province_id: '35', name: 'SAMPANG' },
        { id: '3528', province_id: '35', name: 'PAMEKASAN' },
        { id: '3529', province_id: '35', name: 'SUMENEP' },
        { id: '3571', province_id: '35', name: 'KEDIRI' },
        { id: '3572', province_id: '35', name: 'BLITAR' },
        { id: '3573', province_id: '35', name: 'MALANG' },
        { id: '3574', province_id: '35', name: 'PROBOLINGGO' },
        { id: '3575', province_id: '35', name: 'PASURUAN' },
        { id: '3576', province_id: '35', name: 'MOJOKERTO' },
        { id: '3577', province_id: '35', name: 'MADIUN' },
        { id: '3578', province_id: '35', name: 'SURABAYA' },
        { id: '3579', province_id: '35', name: 'BATU' },
        { id: '3601', province_id: '36', name: 'PANDEGLANG' },
        { id: '3602', province_id: '36', name: 'LEBAK' },
        { id: '3603', province_id: '36', name: 'TANGERANG' },
        { id: '3604', province_id: '36', name: 'SERANG' },
        { id: '3671', province_id: '36', name: 'TANGERANG' },
        { id: '3672', province_id: '36', name: 'CILEGON' },
        { id: '3673', province_id: '36', name: 'SERANG' },
        { id: '3674', province_id: '36', name: 'TANGERANG SELATAN' },
        { id: '5101', province_id: '51', name: 'JEMBRANA' },
        { id: '5102', province_id: '51', name: 'TABANAN' },
        { id: '5103', province_id: '51', name: 'BADUNG' },
        { id: '5104', province_id: '51', name: 'GIANYAR' },
        { id: '5105', province_id: '51', name: 'KLUNGKUNG' },
        { id: '5106', province_id: '51', name: 'BANGLI' },
        { id: '5107', province_id: '51', name: 'KARANG ASEM' },
        { id: '5108', province_id: '51', name: 'BULELENG' },
        { id: '5171', province_id: '51', name: 'DENPASAR' },
        { id: '5201', province_id: '52', name: 'LOMBOK BARAT' },
        { id: '5202', province_id: '52', name: 'LOMBOK TENGAH' },
        { id: '5203', province_id: '52', name: 'LOMBOK TIMUR' },
        { id: '5204', province_id: '52', name: 'SUMBAWA' },
        { id: '5205', province_id: '52', name: 'DOMPU' },
        { id: '5206', province_id: '52', name: 'BIMA' },
        { id: '5207', province_id: '52', name: 'SUMBAWA BARAT' },
        { id: '5208', province_id: '52', name: 'LOMBOK UTARA' },
        { id: '5271', province_id: '52', name: 'MATARAM' },
        { id: '5272', province_id: '52', name: 'BIMA' },
        { id: '5301', province_id: '53', name: 'SUMBA BARAT' },
        { id: '5302', province_id: '53', name: 'SUMBA TIMUR' },
        { id: '5303', province_id: '53', name: 'KUPANG' },
        { id: '5304', province_id: '53', name: 'TIMOR TENGAH SELATAN' },
        { id: '5305', province_id: '53', name: 'TIMOR TENGAH UTARA' },
        { id: '5306', province_id: '53', name: 'BELU' },
        { id: '5307', province_id: '53', name: 'ALOR' },
        { id: '5308', province_id: '53', name: 'LEMBATA' },
        { id: '5309', province_id: '53', name: 'FLORES TIMUR' },
        { id: '5310', province_id: '53', name: 'SIKKA' },
        { id: '5311', province_id: '53', name: 'ENDE' },
        { id: '5312', province_id: '53', name: 'NGADA' },
        { id: '5313', province_id: '53', name: 'MANGGARAI' },
        { id: '5314', province_id: '53', name: 'ROTE NDAO' },
        { id: '5315', province_id: '53', name: 'MANGGARAI BARAT' },
        { id: '5316', province_id: '53', name: 'SUMBA TENGAH' },
        { id: '5317', province_id: '53', name: 'SUMBA BARAT DAYA' },
        { id: '5318', province_id: '53', name: 'NAGEKEO' },
        { id: '5319', province_id: '53', name: 'MANGGARAI TIMUR' },
        { id: '5320', province_id: '53', name: 'SABU RAIJUA' },
        { id: '5321', province_id: '53', name: 'MALAKA' },
        { id: '5371', province_id: '53', name: 'KUPANG' },
        { id: '6101', province_id: '61', name: 'SAMBAS' },
        { id: '6102', province_id: '61', name: 'BENGKAYANG' },
        { id: '6103', province_id: '61', name: 'LANDAK' },
        { id: '6104', province_id: '61', name: 'MEMPAWAH' },
        { id: '6105', province_id: '61', name: 'SANGGAU' },
        { id: '6106', province_id: '61', name: 'KETAPANG' },
        { id: '6107', province_id: '61', name: 'SINTANG' },
        { id: '6108', province_id: '61', name: 'KAPUAS HULU' },
        { id: '6109', province_id: '61', name: 'SEKADAU' },
        { id: '6110', province_id: '61', name: 'MELAWI' },
        { id: '6111', province_id: '61', name: 'KAYONG UTARA' },
        { id: '6112', province_id: '61', name: 'KUBU RAYA' },
        { id: '6171', province_id: '61', name: 'PONTIANAK' },
        { id: '6172', province_id: '61', name: 'SINGKAWANG' },
        { id: '6201', province_id: '62', name: 'KOTAWARINGIN BARAT' },
        { id: '6202', province_id: '62', name: 'KOTAWARINGIN TIMUR' },
        { id: '6203', province_id: '62', name: 'KAPUAS' },
        { id: '6204', province_id: '62', name: 'BARITO SELATAN' },
        { id: '6205', province_id: '62', name: 'BARITO UTARA' },
        { id: '6206', province_id: '62', name: 'SUKAMARA' },
        { id: '6207', province_id: '62', name: 'LAMANDAU' },
        { id: '6208', province_id: '62', name: 'SERUYAN' },
        { id: '6209', province_id: '62', name: 'KATINGAN' },
        { id: '6210', province_id: '62', name: 'PULANG PISAU' },
        { id: '6211', province_id: '62', name: 'GUNUNG MAS' },
        { id: '6212', province_id: '62', name: 'BARITO TIMUR' },
        { id: '6213', province_id: '62', name: 'MURUNG RAYA' },
        { id: '6271', province_id: '62', name: 'PALANGKA RAYA' },
        { id: '6301', province_id: '63', name: 'TANAH LAUT' },
        { id: '6302', province_id: '63', name: 'BARU' },
        { id: '6303', province_id: '63', name: 'BANJAR' },
        { id: '6304', province_id: '63', name: 'BARITO KUALA' },
        { id: '6305', province_id: '63', name: 'TAPIN' },
        { id: '6306', province_id: '63', name: 'HULU SUNGAI SELATAN' },
        { id: '6307', province_id: '63', name: 'HULU SUNGAI TENGAH' },
        { id: '6308', province_id: '63', name: 'HULU SUNGAI UTARA' },
        { id: '6309', province_id: '63', name: 'TABALONG' },
        { id: '6310', province_id: '63', name: 'TANAH BUMBU' },
        { id: '6311', province_id: '63', name: 'BALANGAN' },
        { id: '6371', province_id: '63', name: 'BANJARMASIN' },
        { id: '6372', province_id: '63', name: 'BANJAR BARU' },
        { id: '6401', province_id: '64', name: 'PASER' },
        { id: '6402', province_id: '64', name: 'KUTAI BARAT' },
        { id: '6403', province_id: '64', name: 'KUTAI KARTANEGARA' },
        { id: '6404', province_id: '64', name: 'KUTAI TIMUR' },
        { id: '6405', province_id: '64', name: 'BERAU' },
        { id: '6409', province_id: '64', name: 'PENAJAM PASER UTARA' },
        { id: '6411', province_id: '64', name: 'MAHAKAM HULU' },
        { id: '6471', province_id: '64', name: 'BALIKPAPAN' },
        { id: '6472', province_id: '64', name: 'SAMARINDA' },
        { id: '6474', province_id: '64', name: 'BONTANG' },
        { id: '6501', province_id: '65', name: 'MALINAU' },
        { id: '6502', province_id: '65', name: 'BULUNGAN' },
        { id: '6503', province_id: '65', name: 'TANA TIDUNG' },
        { id: '6504', province_id: '65', name: 'NUNUKAN' },
        { id: '6571', province_id: '65', name: 'TARAKAN' },
        { id: '7101', province_id: '71', name: 'BOLAANG MONGONDOW' },
        { id: '7102', province_id: '71', name: 'MINAHASA' },
        { id: '7103', province_id: '71', name: 'KEPULAUAN SANGIHE' },
        { id: '7104', province_id: '71', name: 'KEPULAUAN TALAUD' },
        { id: '7105', province_id: '71', name: 'MINAHASA SELATAN' },
        { id: '7106', province_id: '71', name: 'MINAHASA UTARA' },
        { id: '7107', province_id: '71', name: 'BOLAANG MONGONDOW UTARA' },
        { id: '7108', province_id: '71', name: 'SIAU TAGULANDANG BIARO' },
        { id: '7109', province_id: '71', name: 'MINAHASA TENGGARA' },
        { id: '7110', province_id: '71', name: 'BOLAANG MONGONDOW SELATAN' },
        { id: '7111', province_id: '71', name: 'BOLAANG MONGONDOW TIMUR' },
        { id: '7171', province_id: '71', name: 'MANADO' },
        { id: '7172', province_id: '71', name: 'BITUNG' },
        { id: '7173', province_id: '71', name: 'TOMOHON' },
        { id: '7174', province_id: '71', name: 'KOTAMOBAGU' },
        { id: '7201', province_id: '72', name: 'BANGGAI KEPULAUAN' },
        { id: '7202', province_id: '72', name: 'BANGGAI' },
        { id: '7203', province_id: '72', name: 'MOROWALI' },
        { id: '7204', province_id: '72', name: 'POSO' },
        { id: '7205', province_id: '72', name: 'DONGGALA' },
        { id: '7206', province_id: '72', name: 'TOLI-TOLI' },
        { id: '7207', province_id: '72', name: 'BUOL' },
        { id: '7208', province_id: '72', name: 'PARIGI MOUTONG' },
        { id: '7209', province_id: '72', name: 'TOJO UNA-UNA' },
        { id: '7210', province_id: '72', name: 'SIGI' },
        { id: '7211', province_id: '72', name: 'BANGGAI LAUT' },
        { id: '7212', province_id: '72', name: 'MOROWALI UTARA' },
        { id: '7271', province_id: '72', name: 'PALU' },
        { id: '7301', province_id: '73', name: 'KEPULAUAN SELAYAR' },
        { id: '7302', province_id: '73', name: 'BULUKUMBA' },
        { id: '7303', province_id: '73', name: 'BANTAENG' },
        { id: '7304', province_id: '73', name: 'JENEPONTO' },
        { id: '7305', province_id: '73', name: 'TAKALAR' },
        { id: '7306', province_id: '73', name: 'GOWA' },
        { id: '7307', province_id: '73', name: 'SINJAI' },
        { id: '7308', province_id: '73', name: 'MAROS' },
        { id: '7309', province_id: '73', name: 'PANGKAJENE DAN KEPULAUAN' },
        { id: '7310', province_id: '73', name: 'BARRU' },
        { id: '7311', province_id: '73', name: 'BONE' },
        { id: '7312', province_id: '73', name: 'SOPPENG' },
        { id: '7313', province_id: '73', name: 'WAJO' },
        { id: '7314', province_id: '73', name: 'SIDENRENG RAPPANG' },
        { id: '7315', province_id: '73', name: 'PINRANG' },
        { id: '7316', province_id: '73', name: 'ENREKANG' },
        { id: '7317', province_id: '73', name: 'LUWU' },
        { id: '7318', province_id: '73', name: 'TANA TORAJA' },
        { id: '7322', province_id: '73', name: 'LUWU UTARA' },
        { id: '7325', province_id: '73', name: 'LUWU TIMUR' },
        { id: '7326', province_id: '73', name: 'TORAJA UTARA' },
        { id: '7371', province_id: '73', name: 'MAKASSAR' },
        { id: '7372', province_id: '73', name: 'PAREPARE' },
        { id: '7373', province_id: '73', name: 'PALOPO' },
        { id: '7401', province_id: '74', name: 'BUTON' },
        { id: '7402', province_id: '74', name: 'MUNA' },
        { id: '7403', province_id: '74', name: 'KONAWE' },
        { id: '7404', province_id: '74', name: 'KOLAKA' },
        { id: '7405', province_id: '74', name: 'KONAWE SELATAN' },
        { id: '7406', province_id: '74', name: 'BOMBANA' },
        { id: '7407', province_id: '74', name: 'WAKATOBI' },
        { id: '7408', province_id: '74', name: 'KOLAKA UTARA' },
        { id: '7409', province_id: '74', name: 'BUTON UTARA' },
        { id: '7410', province_id: '74', name: 'KONAWE UTARA' },
        { id: '7411', province_id: '74', name: 'KOLAKA TIMUR' },
        { id: '7412', province_id: '74', name: 'KONAWE KEPULAUAN' },
        { id: '7413', province_id: '74', name: 'MUNA BARAT' },
        { id: '7414', province_id: '74', name: 'BUTON TENGAH' },
        { id: '7415', province_id: '74', name: 'BUTON SELATAN' },
        { id: '7471', province_id: '74', name: 'KENDARI' },
        { id: '7472', province_id: '74', name: 'BAUBAU' },
        { id: '7501', province_id: '75', name: 'BOALEMO' },
        { id: '7502', province_id: '75', name: 'GORONTALO' },
        { id: '7503', province_id: '75', name: 'POHUWATO' },
        { id: '7504', province_id: '75', name: 'BONE BOLANGO' },
        { id: '7505', province_id: '75', name: 'GORONTALO UTARA' },
        { id: '7571', province_id: '75', name: 'GORONTALO' },
        { id: '7601', province_id: '76', name: 'MAJENE' },
        { id: '7602', province_id: '76', name: 'POLEWALI MANDAR' },
        { id: '7603', province_id: '76', name: 'MAMASA' },
        { id: '7604', province_id: '76', name: 'MAMUJU' },
        { id: '7605', province_id: '76', name: 'MAMUJU UTARA' },
        { id: '7606', province_id: '76', name: 'MAMUJU TENGAH' },
        { id: '8101', province_id: '81', name: 'MALUKU TENGGARA BARAT' },
        { id: '8102', province_id: '81', name: 'MALUKU TENGGARA' },
        { id: '8103', province_id: '81', name: 'MALUKU TENGAH' },
        { id: '8104', province_id: '81', name: 'BURU' },
        { id: '8105', province_id: '81', name: 'KEPULAUAN ARU' },
        { id: '8106', province_id: '81', name: 'SERAM BAGIAN BARAT' },
        { id: '8107', province_id: '81', name: 'SERAM BAGIAN TIMUR' },
        { id: '8108', province_id: '81', name: 'MALUKU BARAT DAYA' },
        { id: '8109', province_id: '81', name: 'BURU SELATAN' },
        { id: '8171', province_id: '81', name: 'AMBON' },
        { id: '8172', province_id: '81', name: 'TUAL' },
        { id: '8201', province_id: '82', name: 'HALMAHERA BARAT' },
        { id: '8202', province_id: '82', name: 'HALMAHERA TENGAH' },
        { id: '8203', province_id: '82', name: 'KEPULAUAN SULA' },
        { id: '8204', province_id: '82', name: 'HALMAHERA SELATAN' },
        { id: '8205', province_id: '82', name: 'HALMAHERA UTARA' },
        { id: '8206', province_id: '82', name: 'HALMAHERA TIMUR' },
        { id: '8207', province_id: '82', name: 'PULAU MOROTAI' },
        { id: '8208', province_id: '82', name: 'PULAU TALIABU' },
        { id: '8271', province_id: '82', name: 'TERNATE' },
        { id: '8272', province_id: '82', name: 'TIDORE KEPULAUAN' },
        { id: '9101', province_id: '91', name: 'FAKFAK' },
        { id: '9102', province_id: '91', name: 'KAIMANA' },
        { id: '9103', province_id: '91', name: 'TELUK WONDAMA' },
        { id: '9104', province_id: '91', name: 'TELUK BINTUNI' },
        { id: '9105', province_id: '91', name: 'MANOKWARI' },
        { id: '9106', province_id: '91', name: 'SORONG SELATAN' },
        { id: '9107', province_id: '91', name: 'SORONG' },
        { id: '9108', province_id: '91', name: 'RAJA AMPAT' },
        { id: '9109', province_id: '91', name: 'TAMBRAUW' },
        { id: '9110', province_id: '91', name: 'MAYBRAT' },
        { id: '9111', province_id: '91', name: 'MANOKWARI SELATAN' },
        { id: '9112', province_id: '91', name: 'PEGUNUNGAN ARFAK' },
        { id: '9171', province_id: '91', name: 'SORONG' },
        { id: '9401', province_id: '94', name: 'MERAUKE' },
        { id: '9402', province_id: '94', name: 'JAYAWIJAYA' },
        { id: '9403', province_id: '94', name: 'JAYAPURA' },
        { id: '9404', province_id: '94', name: 'NABIRE' },
        { id: '9408', province_id: '94', name: 'KEPULAUAN YAPEN' },
        { id: '9409', province_id: '94', name: 'BIAK NUMFOR' },
        { id: '9410', province_id: '94', name: 'PANIAI' },
        { id: '9411', province_id: '94', name: 'PUNCAK JAYA' },
        { id: '9412', province_id: '94', name: 'MIMIKA' },
        { id: '9413', province_id: '94', name: 'BOVEN DIGOEL' },
        { id: '9414', province_id: '94', name: 'MAPPI' },
        { id: '9415', province_id: '94', name: 'ASMAT' },
        { id: '9416', province_id: '94', name: 'YAHUKIMO' },
        { id: '9417', province_id: '94', name: 'PEGUNUNGAN BINTANG' },
        { id: '9418', province_id: '94', name: 'TOLIKARA' },
        { id: '9419', province_id: '94', name: 'SARMI' },
        { id: '9420', province_id: '94', name: 'KEEROM' },
        { id: '9426', province_id: '94', name: 'WAROPEN' },
        { id: '9427', province_id: '94', name: 'SUPIORI' },
        { id: '9428', province_id: '94', name: 'MAMBERAMO RAYA' },
        { id: '9429', province_id: '94', name: 'NDUGA' },
        { id: '9430', province_id: '94', name: 'LANNY JAYA' },
        { id: '9431', province_id: '94', name: 'MAMBERAMO TENGAH' },
        { id: '9432', province_id: '94', name: 'YALIMO' },
        { id: '9433', province_id: '94', name: 'PUNCAK' },
        { id: '9434', province_id: '94', name: 'DOGIYAI' },
        { id: '9435', province_id: '94', name: 'INTAN JAYA' },
        { id: '9436', province_id: '94', name: 'DEIYAI' },
        { id: '9471', province_id: '94', name: 'JAYAPURA' }
      ]);
    });
};
