const uuidv4 = require('uuid/v4');

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('regencies')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('regencies').insert([
        { id: '3401', province_id: '34', name: 'KULON PROGO' },
        { id: '3402', province_id: '34', name: 'BANTUL' },
        { id: '3403', province_id: '34', name: 'GUNUNG KIDUL' },
        { id: '3404', province_id: '34', name: 'SLEMAN' },
        { id: '3471', province_id: '34', name: 'YOGYAKARTA' },
        { id: '3501', province_id: '35', name: 'PACITAN' },
        { id: '3502', province_id: '35', name: 'PONOROGO' },
        { id: '3503', province_id: '35', name: 'TRENGGALEK' },
        { id: '3504', province_id: '35', name: 'TULUNGAGUNG' },
        { id: '3505', province_id: '35', name: 'BLITAR' },
        { id: '3506', province_id: '35', name: 'KEDIRI' },
        { id: '3507', province_id: '35', name: 'MALANG' },
        { id: '3508', province_id: '35', name: 'LUMAJANG' },
        { id: '3509', province_id: '35', name: 'JEMBER' },
        { id: '3510', province_id: '35', name: 'BANYUWANGI' },
        { id: '3511', province_id: '35', name: 'BONDOWOSO' },
        { id: '3512', province_id: '35', name: 'SITUBONDO' },
        { id: '3513', province_id: '35', name: 'PROBOLINGGO' },
        { id: '3514', province_id: '35', name: 'PASURUAN' },
        { id: '3515', province_id: '35', name: 'SIDOARJO' },
        { id: '3516', province_id: '35', name: 'MOJOKERTO' },
        { id: '3517', province_id: '35', name: 'JOMBANG' },
        { id: '3518', province_id: '35', name: 'NGANJUK' },
        { id: '3519', province_id: '35', name: 'MADIUN' },
        { id: '3520', province_id: '35', name: 'MAGETAN' },
        { id: '3521', province_id: '35', name: 'NGAWI' },
        { id: '3522', province_id: '35', name: 'BOJONEGORO' },
        { id: '3523', province_id: '35', name: 'TUBAN' },
        { id: '3524', province_id: '35', name: 'LAMONGAN' },
        { id: '3525', province_id: '35', name: 'GRESIK' },
        { id: '3526', province_id: '35', name: 'BANGKALAN' },
        { id: '3527', province_id: '35', name: 'SAMPANG' },
        { id: '3528', province_id: '35', name: 'PAMEKASAN' },
        { id: '3529', province_id: '35', name: 'SUMENEP' },
        { id: '3571', province_id: '35', name: 'KEDIRI' },
        { id: '3572', province_id: '35', name: 'BLITAR' },
        { id: '3573', province_id: '35', name: 'MALANG' },
        { id: '3574', province_id: '35', name: 'PROBOLINGGO' },
        { id: '3575', province_id: '35', name: 'PASURUAN' },
        { id: '3576', province_id: '35', name: 'MOJOKERTO' },
        { id: '3577', province_id: '35', name: 'MADIUN' },
        { id: '3578', province_id: '35', name: 'SURABAYA' },
        { id: '3579', province_id: '35', name: 'BATU' },
        { id: '3601', province_id: '36', name: 'PANDEGLANG' },
        { id: '3602', province_id: '36', name: 'LEBAK' },
        { id: '3603', province_id: '36', name: 'TANGERANG' },
        { id: '3604', province_id: '36', name: 'SERANG' },
        { id: '3671', province_id: '36', name: 'TANGERANG' },
        { id: '3672', province_id: '36', name: 'CILEGON' },
        { id: '3673', province_id: '36', name: 'SERANG' },
        { id: '3674', province_id: '36', name: 'TANGERANG SELATAN' },
        { id: '5101', province_id: '51', name: 'JEMBRANA' },
        { id: '5102', province_id: '51', name: 'TABANAN' },
        { id: '5103', province_id: '51', name: 'BADUNG' },
        { id: '5104', province_id: '51', name: 'GIANYAR' },
        { id: '5105', province_id: '51', name: 'KLUNGKUNG' },
        { id: '5106', province_id: '51', name: 'BANGLI' },
        { id: '5107', province_id: '51', name: 'KARANG ASEM' },
        { id: '5108', province_id: '51', name: 'BULELENG' },
        { id: '5171', province_id: '51', name: 'DENPASAR' },
        { id: '5201', province_id: '52', name: 'LOMBOK BARAT' },
        { id: '5202', province_id: '52', name: 'LOMBOK TENGAH' },
        { id: '5203', province_id: '52', name: 'LOMBOK TIMUR' },
        { id: '5204', province_id: '52', name: 'SUMBAWA' },
        { id: '5205', province_id: '52', name: 'DOMPU' },
        { id: '5206', province_id: '52', name: 'BIMA' },
        { id: '5207', province_id: '52', name: 'SUMBAWA BARAT' },
        { id: '5208', province_id: '52', name: 'LOMBOK UTARA' },
        { id: '5271', province_id: '52', name: 'MATARAM' },
        { id: '5272', province_id: '52', name: 'BIMA' },
        { id: '5301', province_id: '53', name: 'SUMBA BARAT' },
        { id: '5302', province_id: '53', name: 'SUMBA TIMUR' },
        { id: '5303', province_id: '53', name: 'KUPANG' },
        { id: '5304', province_id: '53', name: 'TIMOR TENGAH SELATAN' },
        { id: '5305', province_id: '53', name: 'TIMOR TENGAH UTARA' },
        { id: '5306', province_id: '53', name: 'BELU' },
        { id: '5307', province_id: '53', name: 'ALOR' },
        { id: '5308', province_id: '53', name: 'LEMBATA' },
        { id: '5309', province_id: '53', name: 'FLORES TIMUR' },
        { id: '5310', province_id: '53', name: 'SIKKA' },
        { id: '5311', province_id: '53', name: 'ENDE' },
        { id: '5312', province_id: '53', name: 'NGADA' },
        { id: '5313', province_id: '53', name: 'MANGGARAI' },
        { id: '5314', province_id: '53', name: 'ROTE NDAO' },
        { id: '5315', province_id: '53', name: 'MANGGARAI BARAT' },
        { id: '5316', province_id: '53', name: 'SUMBA TENGAH' },
        { id: '5317', province_id: '53', name: 'SUMBA BARAT DAYA' },
        { id: '5318', province_id: '53', name: 'NAGEKEO' },
        { id: '5319', province_id: '53', name: 'MANGGARAI TIMUR' },
        { id: '5320', province_id: '53', name: 'SABU RAIJUA' },
        { id: '5321', province_id: '53', name: 'MALAKA' },
        { id: '5371', province_id: '53', name: 'KUPANG' },
        { id: '6101', province_id: '61', name: 'SAMBAS' },
        { id: '6102', province_id: '61', name: 'BENGKAYANG' },
        { id: '6103', province_id: '61', name: 'LANDAK' },
        { id: '6104', province_id: '61', name: 'MEMPAWAH' },
        { id: '6105', province_id: '61', name: 'SANGGAU' },
        { id: '6106', province_id: '61', name: 'KETAPANG' },
        { id: '6107', province_id: '61', name: 'SINTANG' },
        { id: '6108', province_id: '61', name: 'KAPUAS HULU' },
        { id: '6109', province_id: '61', name: 'SEKADAU' },
        { id: '6110', province_id: '61', name: 'MELAWI' },
        { id: '6111', province_id: '61', name: 'KAYONG UTARA' },
        { id: '6112', province_id: '61', name: 'KUBU RAYA' },
        { id: '6171', province_id: '61', name: 'PONTIANAK' },
        { id: '6172', province_id: '61', name: 'SINGKAWANG' },
        { id: '6201', province_id: '62', name: 'KOTAWARINGIN BARAT' },
        { id: '6202', province_id: '62', name: 'KOTAWARINGIN TIMUR' },
        { id: '6203', province_id: '62', name: 'KAPUAS' },
        { id: '6204', province_id: '62', name: 'BARITO SELATAN' },
        { id: '6205', province_id: '62', name: 'BARITO UTARA' }
      ]);
    });
};
