const uuidv4 = require('uuid/v4');

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('regencies')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('regencies').insert([
        { id: '6206', province_id: '62', name: 'SUKAMARA' },
        { id: '6207', province_id: '62', name: 'LAMANDAU' },
        { id: '6208', province_id: '62', name: 'SERUYAN' },
        { id: '6209', province_id: '62', name: 'KATINGAN' },
        { id: '6210', province_id: '62', name: 'PULANG PISAU' },
        { id: '6211', province_id: '62', name: 'GUNUNG MAS' },
        { id: '6212', province_id: '62', name: 'BARITO TIMUR' },
        { id: '6213', province_id: '62', name: 'MURUNG RAYA' },
        { id: '6271', province_id: '62', name: 'PALANGKA RAYA' },
        { id: '6301', province_id: '63', name: 'TANAH LAUT' },
        { id: '6302', province_id: '63', name: 'BARU' },
        { id: '6303', province_id: '63', name: 'BANJAR' },
        { id: '6304', province_id: '63', name: 'BARITO KUALA' },
        { id: '6305', province_id: '63', name: 'TAPIN' },
        { id: '6306', province_id: '63', name: 'HULU SUNGAI SELATAN' },
        { id: '6307', province_id: '63', name: 'HULU SUNGAI TENGAH' },
        { id: '6308', province_id: '63', name: 'HULU SUNGAI UTARA' },
        { id: '6309', province_id: '63', name: 'TABALONG' },
        { id: '6310', province_id: '63', name: 'TANAH BUMBU' },
        { id: '6311', province_id: '63', name: 'BALANGAN' },
        { id: '6371', province_id: '63', name: 'BANJARMASIN' },
        { id: '6372', province_id: '63', name: 'BANJAR BARU' },
        { id: '6401', province_id: '64', name: 'PASER' },
        { id: '6402', province_id: '64', name: 'KUTAI BARAT' },
        { id: '6403', province_id: '64', name: 'KUTAI KARTANEGARA' },
        { id: '6404', province_id: '64', name: 'KUTAI TIMUR' },
        { id: '6405', province_id: '64', name: 'BERAU' },
        { id: '6409', province_id: '64', name: 'PENAJAM PASER UTARA' },
        { id: '6411', province_id: '64', name: 'MAHAKAM HULU' },
        { id: '6471', province_id: '64', name: 'BALIKPAPAN' },
        { id: '6472', province_id: '64', name: 'SAMARINDA' },
        { id: '6474', province_id: '64', name: 'BONTANG' },
        { id: '6501', province_id: '65', name: 'MALINAU' },
        { id: '6502', province_id: '65', name: 'BULUNGAN' },
        { id: '6503', province_id: '65', name: 'TANA TIDUNG' },
        { id: '6504', province_id: '65', name: 'NUNUKAN' },
        { id: '6571', province_id: '65', name: 'TARAKAN' },
        { id: '7101', province_id: '71', name: 'BOLAANG MONGONDOW' },
        { id: '7102', province_id: '71', name: 'MINAHASA' },
        { id: '7103', province_id: '71', name: 'KEPULAUAN SANGIHE' },
        { id: '7104', province_id: '71', name: 'KEPULAUAN TALAUD' },
        { id: '7105', province_id: '71', name: 'MINAHASA SELATAN' },
        { id: '7106', province_id: '71', name: 'MINAHASA UTARA' },
        { id: '7107', province_id: '71', name: 'BOLAANG MONGONDOW UTARA' },
        { id: '7108', province_id: '71', name: 'SIAU TAGULANDANG BIARO' },
        { id: '7109', province_id: '71', name: 'MINAHASA TENGGARA' },
        { id: '7110', province_id: '71', name: 'BOLAANG MONGONDOW SELATAN' },
        { id: '7111', province_id: '71', name: 'BOLAANG MONGONDOW TIMUR' },
        { id: '7171', province_id: '71', name: 'MANADO' },
        { id: '7172', province_id: '71', name: 'BITUNG' },
        { id: '7173', province_id: '71', name: 'TOMOHON' },
        { id: '7174', province_id: '71', name: 'KOTAMOBAGU' },
        { id: '7201', province_id: '72', name: 'BANGGAI KEPULAUAN' },
        { id: '7202', province_id: '72', name: 'BANGGAI' },
        { id: '7203', province_id: '72', name: 'MOROWALI' },
        { id: '7204', province_id: '72', name: 'POSO' },
        { id: '7205', province_id: '72', name: 'DONGGALA' },
        { id: '7206', province_id: '72', name: 'TOLI-TOLI' },
        { id: '7207', province_id: '72', name: 'BUOL' },
        { id: '7208', province_id: '72', name: 'PARIGI MOUTONG' },
        { id: '7209', province_id: '72', name: 'TOJO UNA-UNA' },
        { id: '7210', province_id: '72', name: 'SIGI' },
        { id: '7211', province_id: '72', name: 'BANGGAI LAUT' },
        { id: '7212', province_id: '72', name: 'MOROWALI UTARA' },
        { id: '7271', province_id: '72', name: 'PALU' },
        { id: '7301', province_id: '73', name: 'KEPULAUAN SELAYAR' },
        { id: '7302', province_id: '73', name: 'BULUKUMBA' },
        { id: '7303', province_id: '73', name: 'BANTAENG' },
        { id: '7304', province_id: '73', name: 'JENEPONTO' },
        { id: '7305', province_id: '73', name: 'TAKALAR' },
        { id: '7306', province_id: '73', name: 'GOWA' },
        { id: '7307', province_id: '73', name: 'SINJAI' },
        { id: '7308', province_id: '73', name: 'MAROS' },
        { id: '7309', province_id: '73', name: 'PANGKAJENE DAN KEPULAUAN' },
        { id: '7310', province_id: '73', name: 'BARRU' },
        { id: '7311', province_id: '73', name: 'BONE' },
        { id: '7312', province_id: '73', name: 'SOPPENG' },
        { id: '7313', province_id: '73', name: 'WAJO' },
        { id: '7314', province_id: '73', name: 'SIDENRENG RAPPANG' },
        { id: '7315', province_id: '73', name: 'PINRANG' },
        { id: '7316', province_id: '73', name: 'ENREKANG' },
        { id: '7317', province_id: '73', name: 'LUWU' },
        { id: '7318', province_id: '73', name: 'TANA TORAJA' },
        { id: '7322', province_id: '73', name: 'LUWU UTARA' },
        { id: '7325', province_id: '73', name: 'LUWU TIMUR' },
        { id: '7326', province_id: '73', name: 'TORAJA UTARA' },
        { id: '7371', province_id: '73', name: 'MAKASSAR' },
        { id: '7372', province_id: '73', name: 'PAREPARE' },
        { id: '7373', province_id: '73', name: 'PALOPO' },
        { id: '7401', province_id: '74', name: 'BUTON' },
        { id: '7402', province_id: '74', name: 'MUNA' },
        { id: '7403', province_id: '74', name: 'KONAWE' },
        { id: '7404', province_id: '74', name: 'KOLAKA' },
        { id: '7405', province_id: '74', name: 'KONAWE SELATAN' },
        { id: '7406', province_id: '74', name: 'BOMBANA' },
        { id: '7407', province_id: '74', name: 'WAKATOBI' },
        { id: '7408', province_id: '74', name: 'KOLAKA UTARA' },
        { id: '7409', province_id: '74', name: 'BUTON UTARA' },
        { id: '7410', province_id: '74', name: 'KONAWE UTARA' },
        { id: '7411', province_id: '74', name: 'KOLAKA TIMUR' },
        { id: '7412', province_id: '74', name: 'KONAWE KEPULAUAN' },
        { id: '7413', province_id: '74', name: 'MUNA BARAT' },
        { id: '7414', province_id: '74', name: 'BUTON TENGAH' },
        { id: '7415', province_id: '74', name: 'BUTON SELATAN' },
        { id: '7471', province_id: '74', name: 'KENDARI' },
        { id: '7472', province_id: '74', name: 'BAUBAU' },
        { id: '7501', province_id: '75', name: 'BOALEMO' },
        { id: '7502', province_id: '75', name: 'GORONTALO' },
        { id: '7503', province_id: '75', name: 'POHUWATO' },
        { id: '7504', province_id: '75', name: 'BONE BOLANGO' },
        { id: '7505', province_id: '75', name: 'GORONTALO UTARA' }
      ]);
    });
};
