const uuidv4 = require('uuid/v4');

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('regencies')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('regencies').insert([
        { id: '7571', province_id: '75', name: 'GORONTALO' },
        { id: '7601', province_id: '76', name: 'MAJENE' },
        { id: '7602', province_id: '76', name: 'POLEWALI MANDAR' },
        { id: '7603', province_id: '76', name: 'MAMASA' },
        { id: '7604', province_id: '76', name: 'MAMUJU' },
        { id: '7605', province_id: '76', name: 'MAMUJU UTARA' },
        { id: '7606', province_id: '76', name: 'MAMUJU TENGAH' },
        { id: '8101', province_id: '81', name: 'MALUKU TENGGARA BARAT' },
        { id: '8102', province_id: '81', name: 'MALUKU TENGGARA' },
        { id: '8103', province_id: '81', name: 'MALUKU TENGAH' },
        { id: '8104', province_id: '81', name: 'BURU' },
        { id: '8105', province_id: '81', name: 'KEPULAUAN ARU' },
        { id: '8106', province_id: '81', name: 'SERAM BAGIAN BARAT' },
        { id: '8107', province_id: '81', name: 'SERAM BAGIAN TIMUR' },
        { id: '8108', province_id: '81', name: 'MALUKU BARAT DAYA' },
        { id: '8109', province_id: '81', name: 'BURU SELATAN' },
        { id: '8171', province_id: '81', name: 'AMBON' },
        { id: '8172', province_id: '81', name: 'TUAL' },
        { id: '8201', province_id: '82', name: 'HALMAHERA BARAT' },
        { id: '8202', province_id: '82', name: 'HALMAHERA TENGAH' },
        { id: '8203', province_id: '82', name: 'KEPULAUAN SULA' },
        { id: '8204', province_id: '82', name: 'HALMAHERA SELATAN' },
        { id: '8205', province_id: '82', name: 'HALMAHERA UTARA' },
        { id: '8206', province_id: '82', name: 'HALMAHERA TIMUR' },
        { id: '8207', province_id: '82', name: 'PULAU MOROTAI' },
        { id: '8208', province_id: '82', name: 'PULAU TALIABU' },
        { id: '8271', province_id: '82', name: 'TERNATE' },
        { id: '8272', province_id: '82', name: 'TIDORE KEPULAUAN' },
        { id: '9101', province_id: '91', name: 'FAKFAK' },
        { id: '9102', province_id: '91', name: 'KAIMANA' },
        { id: '9103', province_id: '91', name: 'TELUK WONDAMA' },
        { id: '9104', province_id: '91', name: 'TELUK BINTUNI' },
        { id: '9105', province_id: '91', name: 'MANOKWARI' },
        { id: '9106', province_id: '91', name: 'SORONG SELATAN' },
        { id: '9107', province_id: '91', name: 'SORONG' },
        { id: '9108', province_id: '91', name: 'RAJA AMPAT' },
        { id: '9109', province_id: '91', name: 'TAMBRAUW' },
        { id: '9110', province_id: '91', name: 'MAYBRAT' },
        { id: '9111', province_id: '91', name: 'MANOKWARI SELATAN' },
        { id: '9112', province_id: '91', name: 'PEGUNUNGAN ARFAK' },
        { id: '9171', province_id: '91', name: 'SORONG' },
        { id: '9401', province_id: '94', name: 'MERAUKE' },
        { id: '9402', province_id: '94', name: 'JAYAWIJAYA' },
        { id: '9403', province_id: '94', name: 'JAYAPURA' },
        { id: '9404', province_id: '94', name: 'NABIRE' },
        { id: '9408', province_id: '94', name: 'KEPULAUAN YAPEN' },
        { id: '9409', province_id: '94', name: 'BIAK NUMFOR' },
        { id: '9410', province_id: '94', name: 'PANIAI' },
        { id: '9411', province_id: '94', name: 'PUNCAK JAYA' },
        { id: '9412', province_id: '94', name: 'MIMIKA' },
        { id: '9413', province_id: '94', name: 'BOVEN DIGOEL' },
        { id: '9414', province_id: '94', name: 'MAPPI' },
        { id: '9415', province_id: '94', name: 'ASMAT' },
        { id: '9416', province_id: '94', name: 'YAHUKIMO' },
        { id: '9417', province_id: '94', name: 'PEGUNUNGAN BINTANG' },
        { id: '9418', province_id: '94', name: 'TOLIKARA' },
        { id: '9419', province_id: '94', name: 'SARMI' },
        { id: '9420', province_id: '94', name: 'KEEROM' },
        { id: '9426', province_id: '94', name: 'WAROPEN' },
        { id: '9427', province_id: '94', name: 'SUPIORI' },
        { id: '9428', province_id: '94', name: 'MAMBERAMO RAYA' },
        { id: '9429', province_id: '94', name: 'NDUGA' },
        { id: '9430', province_id: '94', name: 'LANNY JAYA' },
        { id: '9431', province_id: '94', name: 'MAMBERAMO TENGAH' },
        { id: '9432', province_id: '94', name: 'YALIMO' },
        { id: '9433', province_id: '94', name: 'PUNCAK' },
        { id: '9434', province_id: '94', name: 'DOGIYAI' },
        { id: '9435', province_id: '94', name: 'INTAN JAYA' },
        { id: '9436', province_id: '94', name: 'DEIYAI' },
        { id: '9471', province_id: '94', name: 'JAYAPURA' }
      ]);
    });
};
