const uuidv4 = require('uuid/v4');

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('regencies')
    .del()
    .then(function() {
      // Inserts seed entries
      return knex('regencies').insert([
        { id: '1101', province_id: '11', name: 'SIMEULUE' },
        { id: '1102', province_id: '11', name: 'ACEH SINGKIL' },
        { id: '1103', province_id: '11', name: 'ACEH SELATAN' },
        { id: '1104', province_id: '11', name: 'ACEH TENGGARA' },
        { id: '1105', province_id: '11', name: 'ACEH TIMUR' },
        { id: '1106', province_id: '11', name: 'ACEH TENGAH' },
        { id: '1107', province_id: '11', name: 'ACEH BARAT' },
        { id: '1108', province_id: '11', name: 'ACEH BESAR' },
        { id: '1109', province_id: '11', name: 'PIDIE' },
        { id: '1110', province_id: '11', name: 'BIREUEN' },
        { id: '1111', province_id: '11', name: 'ACEH UTARA' },
        { id: '1112', province_id: '11', name: 'ACEH BARAT DAYA' },
        { id: '1113', province_id: '11', name: 'GAYO LUES' },
        { id: '1114', province_id: '11', name: 'ACEH TAMIANG' },
        { id: '1115', province_id: '11', name: 'NAGAN RAYA' },
        { id: '1116', province_id: '11', name: 'ACEH JAYA' },
        { id: '1117', province_id: '11', name: 'BENER MERIAH' },
        { id: '1118', province_id: '11', name: 'PIDIE JAYA' },
        { id: '1171', province_id: '11', name: 'BANDA ACEH' },
        { id: '1172', province_id: '11', name: 'SABANG' },
        { id: '1173', province_id: '11', name: 'LANGSA' },
        { id: '1174', province_id: '11', name: 'LHOKSEUMAWE' },
        { id: '1175', province_id: '11', name: 'SUBULUSSALAM' },
        { id: '1201', province_id: '12', name: 'NIAS' },
        { id: '1202', province_id: '12', name: 'MANDAILING NATAL' },
        { id: '1203', province_id: '12', name: 'TAPANULI SELATAN' },
        { id: '1204', province_id: '12', name: 'TAPANULI TENGAH' },
        { id: '1205', province_id: '12', name: 'TAPANULI UTARA' },
        { id: '1206', province_id: '12', name: 'TOBA SAMOSIR' },
        { id: '1207', province_id: '12', name: 'LABUHAN BATU' },
        { id: '1208', province_id: '12', name: 'ASAHAN' },
        { id: '1209', province_id: '12', name: 'SIMALUNGUN' },
        { id: '1210', province_id: '12', name: 'DAIRI' },
        { id: '1211', province_id: '12', name: 'KARO' },
        { id: '1212', province_id: '12', name: 'DELI SERDANG' },
        { id: '1213', province_id: '12', name: 'LANGKAT' },
        { id: '1214', province_id: '12', name: 'NIAS SELATAN' },
        { id: '1215', province_id: '12', name: 'HUMBANG HASUNDUTAN' },
        { id: '1216', province_id: '12', name: 'PAKPAK BHARAT' },
        { id: '1217', province_id: '12', name: 'SAMOSIR' },
        { id: '1218', province_id: '12', name: 'SERDANG BEDAGAI' },
        { id: '1219', province_id: '12', name: 'BATU BARA' },
        { id: '1220', province_id: '12', name: 'PADANG LAWAS UTARA' },
        { id: '1221', province_id: '12', name: 'PADANG LAWAS' },
        { id: '1222', province_id: '12', name: 'LABUHAN BATU SELATAN' },
        { id: '1223', province_id: '12', name: 'LABUHAN BATU UTARA' },
        { id: '1224', province_id: '12', name: 'NIAS UTARA' },
        { id: '1225', province_id: '12', name: 'NIAS BARAT' },
        { id: '1271', province_id: '12', name: 'SIBOLGA' },
        { id: '1272', province_id: '12', name: 'TANJUNG BALAI' },
        { id: '1273', province_id: '12', name: 'PEMATANG SIANTAR' },
        { id: '1274', province_id: '12', name: 'TEBING TINGGI' },
        { id: '1275', province_id: '12', name: 'MEDAN' },
        { id: '1276', province_id: '12', name: 'BINJAI' },
        { id: '1277', province_id: '12', name: 'PADANGSIDIMPUAN' },
        { id: '1278', province_id: '12', name: 'GUNUNGSITOLI' },
        { id: '1301', province_id: '13', name: 'KEPULAUAN MENTAWAI' },
        { id: '1302', province_id: '13', name: 'PESISIR SELATAN' },
        { id: '1303', province_id: '13', name: 'SOLOK' },
        { id: '1304', province_id: '13', name: 'SIJUNJUNG' },
        { id: '1305', province_id: '13', name: 'TANAH DATAR' },
        { id: '1306', province_id: '13', name: 'PADANG PARIAMAN' },
        { id: '1307', province_id: '13', name: 'AGAM' },
        { id: '1308', province_id: '13', name: 'LIMA PULUH KOTA' },
        { id: '1309', province_id: '13', name: 'PASAMAN' },
        { id: '1310', province_id: '13', name: 'SOLOK SELATAN' },
        { id: '1311', province_id: '13', name: 'DHARMASRAYA' },
        { id: '1312', province_id: '13', name: 'PASAMAN BARAT' },
        { id: '1371', province_id: '13', name: 'PADANG' },
        { id: '1372', province_id: '13', name: 'SOLOK' },
        { id: '1373', province_id: '13', name: 'SAWAH LUNTO' },
        { id: '1374', province_id: '13', name: 'PADANG PANJANG' },
        { id: '1375', province_id: '13', name: 'BUKITTINGGI' },
        { id: '1376', province_id: '13', name: 'PAYAKUMBUH' },
        { id: '1377', province_id: '13', name: 'PARIAMAN' },
        { id: '1401', province_id: '14', name: 'KUANTAN SINGINGI' },
        { id: '1402', province_id: '14', name: 'INDRAGIRI HULU' },
        { id: '1403', province_id: '14', name: 'INDRAGIRI HILIR' },
        { id: '1404', province_id: '14', name: 'PELALAWAN' },
        { id: '1405', province_id: '14', name: 'S I A K' },
        { id: '1406', province_id: '14', name: 'KAMPAR' },
        { id: '1407', province_id: '14', name: 'ROKAN HULU' },
        { id: '1408', province_id: '14', name: 'BENGKALIS' },
        { id: '1409', province_id: '14', name: 'ROKAN HILIR' },
        { id: '1410', province_id: '14', name: 'KEPULAUAN MERANTI' },
        { id: '1471', province_id: '14', name: 'PEKANBARU' },
        { id: '1473', province_id: '14', name: 'D U M A I' },
        { id: '1501', province_id: '15', name: 'KERINCI' },
        { id: '1502', province_id: '15', name: 'MERANGIN' },
        { id: '1503', province_id: '15', name: 'SAROLANGUN' },
        { id: '1504', province_id: '15', name: 'BATANG HARI' },
        { id: '1505', province_id: '15', name: 'MUARO JAMBI' },
        { id: '1506', province_id: '15', name: 'TANJUNG JABUNG TIMUR' },
        { id: '1507', province_id: '15', name: 'TANJUNG JABUNG BARAT' },
        { id: '1508', province_id: '15', name: 'TEBO' },
        { id: '1509', province_id: '15', name: 'BUNGO' },
        { id: '1571', province_id: '15', name: 'JAMBI' },
        { id: '1572', province_id: '15', name: 'SUNGAI PENUH' },
        { id: '1601', province_id: '16', name: 'OGAN KOMERING ULU' },
        { id: '1602', province_id: '16', name: 'OGAN KOMERING ILIR' },
        { id: '1603', province_id: '16', name: 'MUARA ENIM' },
        { id: '1604', province_id: '16', name: 'LAHAT' },
        { id: '1605', province_id: '16', name: 'MUSI RAWAS' },
        { id: '1606', province_id: '16', name: 'MUSI BANYUASIN' },
        { id: '1607', province_id: '16', name: 'BANYU ASIN' },
        { id: '1608', province_id: '16', name: 'OGAN KOMERING ULU SELATAN' },
        { id: '1609', province_id: '16', name: 'OGAN KOMERING ULU TIMUR' },
        { id: '1610', province_id: '16', name: 'OGAN ILIR' },
        { id: '1611', province_id: '16', name: 'EMPAT LAWANG' },
        { id: '1612', province_id: '16', name: 'PENUKAL ABAB LEMATANG ILIR' },
        { id: '1613', province_id: '16', name: 'MUSI RAWAS UTARA' }
      ]);
    });
};
